### ISSUE TITLE
source files ? 

### ISSUE THREAD

**Issue by tx4x** [hakkens/precious-plastic-kit#11]
hi,
i'd like to work on the v3 kit (as discussed in the forum). I am missing the source files to create the PDF manuals, I don't mind too much about the material-bill files since I am more likely to recreate them via xls to markdown|pdf tools. 

Not sure where the source files for the websites are ('machines' section),  are that wordpress articles ? 

guenter

**Comment by tx4x** [comment]
ok, at the end, another 2 hours wasted....

**Comment by re404** [comment]
Good point ... maybe Dave should upload the (Illustrator / Indesign ?) layout files he used, so that people can edit and upload changes...
I'm afraid that these binary files won't work very well with github so it would be nice that in the future that get converterd into an open (ascii based) format. (PDF'able HTML+CSS or something ?)

**Comment by re404** [comment]
The source files that I think you mean are all 3D CAD files in different formats by the way.
